### ISSUE TITLE
rust-crate.eclass uses invalid TARGET (CHOST value is legal for gentoo, but not rust )

### ISSUE THREAD

**Issue by kentfredric** [kentnl-gentoo-rust/rust-dev-overlay#3]
```bash
#  /usr/bin/rustc --target x86_64-pc-linux-gnu
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

```

This becomes obvious when running tests for autocfg, which fail under gentoo's portage environment, but pass run in a rustup environment.

```bash
# cargo +system test -q

running 10 tests
..error[E0463]: can't find crate for `probe`
 --> <anon>:1:1
  |
1 | extern crate doesnt_exist as probe;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
.warning: trait objects without an explicit `dyn` are deprecated
 --> <anon>:1:18
  |
1 | pub type Probe = std::convert::AsRef<str>;
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn std::convert::AsRef<str>`
  |
  = note: #[warn(bare_trait_objects)] on by default

..warning: trait objects without an explicit `dyn` are deprecated
 --> <anon>:1:18
  |
1 | pub type Probe = std::ops::Add<i32, Output = i32>;
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn std::ops::Add<i32, Output = i32>`
  |
  = note: #[warn(bare_trait_objects)] on by default

....warning: trait objects without an explicit `dyn` are deprecated
 --> <anon>:1:18
  |
1 | pub type Probe = std::iter::Sum<i32>;
  |                  ^^^^^^^^^^^^^^^^^^^ help: use `dyn`: `dyn std::iter::Sum<i32>`
  |
  = note: #[warn(bare_trait_objects)] on by default

.
test result: ok. 10 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out


running 5 tests
test src/lib.rs - AutoCfg::probe_path (line 238) ... ignored
test src/lib.rs - AutoCfg::probe_sysroot_crate (line 219) ... ignored
test src/lib.rs - AutoCfg::probe_trait (line 266) ... ignored
test src/lib.rs - AutoCfg::probe_type (line 295) ... ignored
test src/lib.rs -  (line 18) ... ok

test result: ok. 1 passed; 0 failed; 4 ignored; 0 measured; 0 filtered out
```
```bash
# TARGET="x86_64-pc-linux-gnu" cargo +system test -q

running 10 tests
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

warning: autocfg could not probe for `std`
.error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

warning: autocfg could not probe for `std`
warning: autocfg could not probe for `std`
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

warning: autocfg could not probe for `std`
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

FFerror: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

Ferror: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

warning: autocfg could not probe for `std`
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

warning: autocfg could not probe for `std`
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

warning: autocfg could not probe for `std`
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

warning: autocfg could not probe for `std`
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

.F.error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

Ferror: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

Ferror: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

warning: autocfg could not probe for `std`
error: Error loading target specification: Could not find specification for target "x86_64-pc-linux-gnu"
  |
  = help: Use `--print target-list` for a list of built-in targets

F
failures:

---- tests::probe_alloc stdout ----
thread 'tests::probe_alloc' panicked at 'assertion failed: missing ^ ac.probe_sysroot_crate("alloc")', src/tests.rs:84:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- tests::probe_as_ref stdout ----
thread 'tests::probe_as_ref' panicked at 'assertion failed: ac.probe_path(&as_ref)', src/tests.rs:48:5

---- tests::probe_add stdout ----
thread 'tests::probe_add' panicked at 'assertion failed: ac.probe_path(&add)', src/tests.rs:36:5

---- tests::probe_i128 stdout ----
thread 'tests::probe_i128' panicked at 'assertion failed: missing ^ ac.probe_path(&i128_path)', src/tests.rs:58:5

---- tests::probe_no_std stdout ----
thread 'tests::probe_no_std' panicked at 'assertion failed: ac.probe_type("i32")', src/tests.rs:96:5

---- tests::probe_std stdout ----
thread 'tests::probe_std' panicked at 'assertion failed: `(left == right)`
  left: `false`,
 right: `true`', src/tests.rs:77:5

---- tests::probe_sum stdout ----
thread 'tests::probe_sum' panicked at 'assertion failed: missing ^ ac.probe_path(&sum)', src/tests.rs:68:5


failures:
    tests::probe_add
    tests::probe_alloc
    tests::probe_as_ref
    tests::probe_i128
    tests::probe_no_std
    tests::probe_std
    tests::probe_sum

test result: FAILED. 3 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out
```

```bash
# grep -B2 CHOST= /etc/portage/make.conf
# WARNING: Changing your CHOST is not something that should be done lightly.
# Please consult http://www.gentoo.org/doc/en/change-chost.xml before changing.
CHOST="x86_64-pc-linux-gnu"
```
```bash
# /usr/bin/rustc --print target-list | grep x86
x86_64-apple-darwin
x86_64-fortanix-unknown-sgx
x86_64-fuchsia
x86_64-linux-android
x86_64-pc-solaris
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc
x86_64-rumprun-netbsd
x86_64-sun-solaris
x86_64-unknown-cloudabi
x86_64-unknown-dragonfly
x86_64-unknown-freebsd
x86_64-unknown-haiku
x86_64-unknown-hermit
x86_64-unknown-l4re-uclibc
x86_64-unknown-linux-gnu
x86_64-unknown-linux-gnux32
x86_64-unknown-linux-musl
x86_64-unknown-netbsd
x86_64-unknown-openbsd
x86_64-unknown-redox
x86_64-unknown-uefi
```
```bash
# grep "export TARGET" /var/db/repos/rust-dev/eclass/rust-crate.eclass
export TARGET="${CHOST}"
export TARGET_CC="$(tc-getCC)"
```
```bash
# grep "[-]x TARGET" '/var/tmp/portage/dev-rust/autocfg-0.1.6/temp/environment'
declare -x TARGET="x86_64-pc-linux-gnu"
declare -x TARGET_CC="x86_64-pc-linux-gnu-gcc"
```
```bash
# grep HOST /usr/portage/profiles/arch/amd64/make.defaults 
CHOST="x86_64-pc-linux-gnu"
CHOST_amd64="x86_64-pc-linux-gnu"
CHOST_x86="i686-pc-linux-gnu"
CHOST_x32="x86_64-pc-linux-gnux32"
```

**Comment by gyakovlev** [comment]
`rust-toolchain.eclass` (which is in the ::gentoo tree) has some target translation logic we could use here. it's not perfect but should prevent this I think
